# Generated by Django 5.0.9 on 2026-09-24 09:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(blank=True, max_length=128)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("whatsapp", models.CharField(blank=True, max_length=32)),
                ("job_title", models.CharField(blank=True, max_length=128)),
                ("website", models.URLField(blank=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=128)),
                ("country", models.CharField(blank=True, max_length=128)),
                (
                    "lead_source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("google", "Google"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("referral", "Referral"),
                            ("direct", "Direct"),
                            ("import", "Import"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "lead_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("connected", "Connected"),
                            ("bad_timing", "Bad Timing"),
                            ("unqualified", "Unqualified"),
                        ],
                        default="new",
                        max_length=32,
                    ),
                ),
                (
                    "lifecycle_stage",
                    models.CharField(
                        choices=[
                            ("subscriber", "Subscriber"),
                            ("lead", "Lead"),
                            ("mql", "Marketing Qualified Lead"),
                            ("sql", "Sales Qualified Lead"),
                            ("opportunity", "Opportunity"),
                            ("customer", "Customer"),
                            ("evangelist", "Evangelist"),
                            ("other", "Other"),
                        ],
                        default="lead",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="contact_avatars/"
                    ),
                ),
                ("lead_score", models.IntegerField(default=0)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("last_contacted_at", models.DateTimeField(blank=True, null=True)),
                ("next_follow_up_at", models.DateTimeField(blank=True, null=True)),
                ("utm_source", models.CharField(blank=True, max_length=128)),
                ("utm_medium", models.CharField(blank=True, max_length=128)),
                ("utm_campaign", models.CharField(blank=True, max_length=128)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="contacts", to="core.tag"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "email"],
                        name="contacts_co_organiz_dced60_idx",
                    ),
                    models.Index(
                        fields=["organization", "last_name", "first_name"],
                        name="contacts_co_organiz_02e43b_idx",
                    ),
                ],
            },
        ),
    ]
