import type { Metadata } from "next";

export const metadata: Metadata = { title: "Terms of Service" };

export default function TermsPage() {
  return (
    <div className="container max-w-2xl py-16">
      <h1 className="font-serif text-3xl font-semibold">Terms of Service</h1>
      <div className="mt-8 space-y-6 text-sm leading-relaxed text-muted-foreground">
        <section>
          <h2 className="font-serif text-lg text-foreground">Use of the service</h2>
          <p>
            STYLEAI provides AI-generated style recommendations and virtual try-on previews for personal,
            non-commercial use. Recommendations are generated by AI and provided as styling guidance, not
            professional or medical advice.
          </p>
        </section>
        <section>
          <h2 className="font-serif text-lg text-foreground">Free and Pro plans</h2>
          <p>
            The Free plan includes a limited number of AI generations per month. The Pro plan removes this
            limit and unlocks advanced virtual try-on and premium recommendations. Plan details are shown at
            checkout.
          </p>
        </section>
        <section>
          <h2 className="font-serif text-lg text-foreground">Shopping and affiliate links</h2>
          <p>
            Product listings in Shopping Mode may include affiliate links. STYLEAI may earn a commission on
            purchases made through these links at no extra cost to you. Product availability and pricing are
            provided by connected retailers and are not guaranteed by STYLEAI.
          </p>
        </section>
        <section>
          <h2 className="font-serif text-lg text-foreground">Account termination</h2>
          <p>You may delete your account at any time from Dashboard → Settings.</p>
        </section>
      </div>
    </div>
  );
}
